name: Importer les données ETF chaque jour ouvré

on:
  schedule:
    - cron: '0 16 * * 1-5'  # Du lundi au vendredi à 16h UTC (18h heure française en été)
  workflow_dispatch:        # Permet de le lancer manuellement aussi

jobs:
  import_data:
    runs-on: ubuntu-latest

    env:
      EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-prod.txt
          pip install python-dotenv

      - name: Lancer le script d'import pour DTLA
        run: python imports/import_bq_DTLA.py

      - name: Lancer le script d'import pour eur_usd_parity
        run: python imports/import_bq_eur_usd_parity.py

      - name: Lancer le script d'import pour XD9U
        run: python imports/import_bq_XD9U.py

      - name: Lancer le script d'import pour XGDU
        run: python imports/import_bq_XGDU.py

      - name: Lancer le script d'import pour ZPR1
        run: python imports/import_bq_ZPR1.py