name: Importer les données ETF chaque jour ouvré

on:
  schedule:
    - cron: '0 5 * * 0'  # Tous les dimanches à 5h UTC (7h heure française en été)
  workflow_dispatch:        # Permet de le lancer manuellement aussi

jobs:
  import_data:
    runs-on: ubuntu-latest

    env:
      EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-prod.txt
          pip install python-dotenv

      - name: Lancer le script d'import pour XD9U
        run: python imports/import_bq_XD9U.py

      - name: Lancer le script d'import pour DELG
        run: python imports/import_bq_DELG.py

      - name: Lancer le script d'import pour R1VL
        run: python imports/import_bq_R1VL.py